org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# Gateway 的实际对外 HTTPS 域名
wristbrief.gatewayBaseUrl=https://wbapi.underflo.ink
# 前面在 Google Cloud 创建的 Web Application Client ID（注意不是 Android Client ID）
wristbrief.googleWebClientId=281918668702-40k2h33bktm7tom7srirkmolf7b543ub.apps.googleusercontent.com