package ink.underflo.wristbrief.mobile.audio

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.defaultMinSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.LiveRegionMode
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.liveRegion
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.stateDescription
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import ink.underflo.wristbrief.mobile.R
import ink.underflo.wristbrief.mobile.ui.AppIcon
import ink.underflo.wristbrief.mobile.ui.AppIconKind
import ink.underflo.wristbrief.mobile.ui.MobileSpacing
import ink.underflo.wristbrief.mobile.ui.TouchTargetTokens
import ink.underflo.wristbrief.mobile.ui.glass.GlassSurface
import ink.underflo.wristbrief.mobile.ui.glass.GlassTokens

/**
 * Short-text speech preview ("试听").
 *
 * Only a bounded sample can be read aloud today: the gateway's `POST /v1/audio/speech`
 * accepts at most 2000 characters and returns a single MP3. Long-form narration is not a
 * feature, so this card says so and points at the system reader instead of pretending
 * the whole article can be played.
 */
@Composable
fun SpeechPreviewCard(
    state: SpeechPreviewUiState,
    onPlayPause: (SpeechPreviewRequest) -> Unit,
    onRetry: (SpeechPreviewRequest) -> Unit,
    onStop: () -> Unit,
    modifier: Modifier = Modifier,
    darkTheme: Boolean = androidx.compose.foundation.isSystemInDarkTheme(),
) {
    // Survives a configuration change or process death, so a half-typed sample is not lost.
    var previewText by rememberSaveable { mutableStateOf("") }
    val request = SpeechPreviewRequest(previewText)
    val overLimit = !request.isWithinLimit
    val previewStateLabel = speechPreviewStateDescription(state)

    GlassSurface(
        modifier = modifier
            .fillMaxWidth()
            .testTag("speech_preview_card"),
        cornerRadius = GlassTokens.CardRadius,
        strong = false,
        darkTheme = darkTheme,
    ) {
        Column(
            modifier = Modifier.padding(MobileSpacing.medium),
            verticalArrangement = Arrangement.spacedBy(MobileSpacing.small),
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(MobileSpacing.small),
            ) {
                AppIcon(AppIconKind.Microphone, Modifier.size(18.dp), GlassTokens.accentTeal(darkTheme))
                Text(
                    text = stringResource(R.string.speech_preview_title),
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.SemiBold,
                    color = GlassTokens.textPrimary(darkTheme),
                    modifier = Modifier.semantics { heading() },
                )
            }

            Text(
                text = stringResource(R.string.speech_preview_body),
                style = MaterialTheme.typography.bodySmall,
                color = GlassTokens.textSecondary(darkTheme),
            )

            // Mandatory disclosure: the voice is generated by an AI provider, not a person.
            Surface(
                shape = RoundedCornerShape(8.dp),
                color = GlassTokens.surfaceContainerHigh(darkTheme),
                modifier = Modifier
                    .fillMaxWidth()
                    .testTag("speech_preview_disclosure"),
            ) {
                Text(
                    text = stringResource(R.string.speech_preview_ai_voice_disclosure),
                    style = MaterialTheme.typography.labelMedium,
                    color = GlassTokens.textPrimary(darkTheme),
                    modifier = Modifier.padding(horizontal = MobileSpacing.small, vertical = 6.dp),
                )
            }

            OutlinedTextField(
                value = previewText,
                onValueChange = { previewText = it },
                modifier = Modifier
                    .fillMaxWidth()
                    .testTag("speech_preview_input"),
                label = { Text(stringResource(R.string.speech_preview_input_label)) },
                placeholder = { Text(stringResource(R.string.speech_preview_input_hint)) },
                minLines = 2,
                maxLines = 5,
                shape = RoundedCornerShape(12.dp),
            )

            Text(
                text = stringResource(
                    R.string.speech_preview_character_count,
                    request.characterCount,
                    SpeechPreviewRequest.MAX_CHARACTERS,
                ),
                style = MaterialTheme.typography.labelSmall,
                color = if (overLimit) MaterialTheme.colorScheme.error else GlassTokens.textSecondary(darkTheme),
                modifier = Modifier.testTag("speech_preview_counter"),
            )
            if (overLimit) {
                // Its own line: the message is long in both languages and must wrap on a
                // narrow screen rather than being squeezed beside the counter.
                Text(
                    text = stringResource(R.string.speech_preview_over_limit),
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier
                        .fillMaxWidth()
                        .testTag("speech_preview_over_limit"),
                )
            }

            state.issue?.let { issue ->
                SpeechPreviewIssueBanner(issue = issue, darkTheme = darkTheme)
            }

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(MobileSpacing.small),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Button(
                    onClick = { onPlayPause(request) },
                    enabled = request.isSendable && !state.isGenerating,
                    modifier = Modifier
                        .weight(1f)
                        .defaultMinSize(minHeight = TouchTargetTokens.minTouchTarget)
                        .testTag("speech_preview_play_button")
                        .semantics { stateDescription = previewStateLabel },
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = GlassTokens.primaryContainer(darkTheme),
                        contentColor = GlassTokens.accentTeal(darkTheme),
                    ),
                ) {
                    if (state.isGenerating) {
                        CircularProgressIndicator(
                            modifier = Modifier.size(18.dp),
                            strokeWidth = 2.dp,
                            color = GlassTokens.accentTeal(darkTheme),
                        )
                        Spacer(modifier = Modifier.width(MobileSpacing.small))
                        Text(stringResource(R.string.speech_preview_loading))
                    } else {
                        AppIcon(
                            kind = if (state.isPlaying) AppIconKind.Pause else AppIconKind.Play,
                            modifier = Modifier.size(18.dp),
                            tint = GlassTokens.accentTeal(darkTheme),
                        )
                        Spacer(modifier = Modifier.width(MobileSpacing.small))
                        Text(
                            text = stringResource(
                                if (state.isPlaying) {
                                    R.string.speech_preview_pause
                                } else {
                                    R.string.speech_preview_play
                                },
                            ),
                        )
                    }
                }

                if (state.issue?.canRetry == true) {
                    OutlinedButton(
                        onClick = { onRetry(request) },
                        modifier = Modifier
                            .defaultMinSize(minHeight = TouchTargetTokens.minTouchTarget)
                            .testTag("speech_preview_retry_button"),
                        shape = RoundedCornerShape(12.dp),
                    ) {
                        Text(
                            text = stringResource(R.string.speech_preview_retry),
                            color = GlassTokens.textPrimary(darkTheme),
                        )
                    }
                }

                if (state.canStop) {
                    OutlinedButton(
                        onClick = onStop,
                        modifier = Modifier
                            .defaultMinSize(minHeight = TouchTargetTokens.minTouchTarget)
                            .testTag("speech_preview_stop_button"),
                        shape = RoundedCornerShape(12.dp),
                    ) {
                        Text(
                            text = stringResource(R.string.speech_preview_stop),
                            color = GlassTokens.textPrimary(darkTheme),
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                        )
                    }
                }
            }

            Text(
                text = stringResource(R.string.speech_preview_long_form_unavailable),
                style = MaterialTheme.typography.bodySmall,
                color = GlassTokens.textSecondary(darkTheme),
            )
        }
    }
}

@Composable
private fun SpeechPreviewIssueBanner(issue: SpeechPreviewIssue, darkTheme: Boolean) {
    Surface(
        shape = RoundedCornerShape(8.dp),
        color = MaterialTheme.colorScheme.errorContainer,
        modifier = Modifier
            .fillMaxWidth()
            .testTag("speech_preview_error")
            .semantics { liveRegion = LiveRegionMode.Polite },
    ) {
        Text(
            text = stringResource(speechPreviewIssueMessageRes(issue.reason)),
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onErrorContainer,
            modifier = Modifier.padding(horizontal = MobileSpacing.small, vertical = 6.dp),
        )
    }
}

/** One honest sentence per failure cause; no generic "something went wrong" for known cases. */
@Composable
fun speechPreviewIssueMessageRes(reason: SpeechPreviewIssueReason): Int = when (reason) {
    SpeechPreviewIssueReason.NETWORK -> R.string.speech_preview_error_network
    SpeechPreviewIssueReason.UNAUTHORIZED -> R.string.speech_preview_error_unauthorized
    SpeechPreviewIssueReason.QUOTA_UNAVAILABLE -> R.string.speech_preview_error_quota
    SpeechPreviewIssueReason.TEXT_TOO_LONG -> R.string.speech_preview_error_too_long
    SpeechPreviewIssueReason.TEXT_INVALID -> R.string.speech_preview_error_invalid_text
    SpeechPreviewIssueReason.PROVIDER_UNAVAILABLE -> R.string.speech_preview_error_provider
    SpeechPreviewIssueReason.GENERATION_FAILED -> R.string.speech_preview_error_generation
    SpeechPreviewIssueReason.SERVER_GONE -> R.string.speech_preview_error_unavailable
}

/** Accessibility label for the current preview state, used by the play/pause control. */
@Composable
fun speechPreviewStateDescription(state: SpeechPreviewUiState): String = when {
    state.issue != null -> stringResource(speechPreviewIssueMessageRes(state.issue.reason))
    state.isGenerating -> stringResource(R.string.speech_preview_loading)
    state.isPlaying -> stringResource(R.string.speech_preview_pause)
    else -> stringResource(R.string.speech_preview_play)
}
